### ISSUE TITLE
[Question] Is abilities persistent after death?

### ISSUE THREAD

**Issue by eliskvitka** [Ladysnake/PlayerAbilityLib#14]
I am using this library in my own mod and it looks like abilities don't persist after death
Or maybe i am using it wrong? You can take a look [here](https://github.com/eliskvitka/toggle-pvp/blob/master/src/main/java/me/braunly/togglepvp/PvpAbility.java)

**Comment by Pyrofab** [comment]
Correct, there is no included mechanism for persistence after death. Depending on your use case, you could use something like Cardinal Components API to persist data, or just a mixin to `ServerPlayerEntity#copyFrom`.

**Comment by eliskvitka** [comment]
> Correct, there is no included mechanism for persistence after death. Depending on your use case, you could use something like Cardinal Components API to persist data, or just a mixin to `ServerPlayerEntity#copyFrom`.

Okay, I get it
Thank you
