### ISSUE TITLE
Console spam when quantum armor from tech reborn is used.

### ISSUE THREAD

**Issue by TheNanuak** [Ladysnake/PlayerAbilityLib#16]
On my Minecraft 1.20.1 server running fabric if a player uses quantum armour the console is spammed with the same error,
here is the paste https://pastebin.com/mbSt4wWj
and here is the link to the issue I opened on tech reborn's Git Hub.
https://github.com/TechReborn/TechReborn/issues/3176

**Comment by Trent2087** [comment]
This is not just console spam. It is also breaking TR quantum armor flight now in 1.20. In previous MC versions it just spammed the console. Now it breaking TR flight and spamming the console.

**Comment by burdoto** [comment]
Related to https://github.com/TechReborn/TechReborn/issues/3186.

Causes log files to MASSIVELY increase in size and become unhandleable.
This is an urgent fix.

**Comment by lexi-the-cute** [comment]
TechReborn refuses to add PAL cause of not wanting to rely on dependencies that may delay updating. Is there a way to configure the ability ignore specific mods when they modify the player attributes without PAL? also is there a way to depend on PAL only if it's detected as a loaded mod?

https://github.com/TechReborn/TechReborn/pull/3241

**Comment by burdoto** [comment]
@lexi-the-cute at that point might just be better to make a fork to remove this stupid warning, as even when it comes up nothing is affected

**Comment by Pyrofab** [comment]
Nothing is affected until you use another mod that can grant you flight - but I'll do something about the console spam, it's not intended behaviour.

**Comment by burdoto** [comment]
this turns a bit unrelated, but why is it affected when more than one mod comes into play?
as long as you read and write _directly_ to and from the vanilla attribute; everything should be fine?
rather; why would i want to introduce a reiteration of an existing vanilla attribute that will need to be in sync with the vanilla attribute?

**Comment by Pyrofab** [comment]
The issue is the following scenario :

- Mod A enables flight because a player drank a potion
- Mod B enables flight because the player toggled its jetpack
- Mod A disables flight because its potion effect ran out
- Flight is disabled -> the player crashes down despite the jetpack still being active

This is why PlayerAbilityLib exists

**Comment by burdoto** [comment]
That makes a lot of sense actually, thank you for the heads-up

**Comment by Pyrofab** [comment]
As of 1.11.0, the config option making it so warnings are logged only once per game session is enabled by default, which should fix the spam.
