### ISSUE TITLE
Not working in 1.16-pre6+

### ISSUE THREAD

**Issue by lucaargolo** [Ladysnake/PlayerAbilityLib#3]
This one is pretty self-explanatory, I guess. PAL is working fine up to 1.16-pre5 but it fails to apply its mixins on pre6 and pre7. Tested it using both [Kibe](https://github.com/lucaargolo/kibe) and [Winged](https://github.com/adriantodt/Winged)
[crash-2020-06-16_21.23.16-server.txt](https://github.com/Ladysnake/PlayerAbilityLib/files/4790040/crash-2020-06-16_21.23.16-server.txt)

**Comment by Linguardium** [comment]
looks like `setGameMode(GameMode gameMode)` is now `setGameMode(GameMode gameMode, GameMode gameMode2)`
