### ISSUE TITLE
Removing Flight Status Effect

### ISSUE THREAD

**Issue by iamshift** [Ladysnake/PlayerAbilityLib#4]
My mod adds a new buff to beacon that allows players to fly in survival while inside the beacon area.
But every 3 seconds this mod is removing the fly status if the player is in survival.

Mod: [Big Extras](https://www.curseforge.com/minecraft/mc-mods/big-extras-fabric)
[warn.txt](https://github.com/Ladysnake/PlayerAbilityLib/files/5385823/warn.txt)

**Comment by Pyrofab** [comment]
I would strongly suggest you start using this library instead. Not doing so will result in incompatibilities with every mod you mentioned regardless.

**Comment by iamshift** [comment]
By adding this and doing some cleaning I was able to fix the problem.
I'm closing this issue because is no longer relevant.
