### ISSUE TITLE
switching dimensions removes ability to use creative fly

### ISSUE THREAD

**Issue by Nachtalb** [Ladysnake/PlayerAbilityLib#7]
So after teleporting to another dimension creative flight doesn't seem to be usable anymore in survival.
I stumbled upon that on [FabricHomes](https://curseforge.com/minecraft/mc-mods/fabrichomes) and [FabricWarps](https://curseforge.com/minecraft/mc-mods/fabricwarps) which lead me to create this issue 
 https://github.com/CodedSakura/FabricWarps/issues/2 followed by this https://github.com/CafeteriaGuild/Winged/issues/32 (as the flying was enabled by [Winged](https://www.curseforge.com/minecraft/mc-mods/winged). Which now finally [lead](https://github.com/CafeteriaGuild/Winged/issues/32#issuecomment-862571339) me to here as your lib seems to manage the flight ability. 

After TPing to another dimension in survival, I am not able to fly anymore. ATM, the problem can be worked around by switching to creative then back to survival. But that is only possible for OPs.

In the other issues mentioned above is a video in case you want to see the bug in "live-action" so to say.

Example fix for status effects and exp bar from the tp mod as reference: https://github.com/CodedSakura/FabricWarps/issues/2#issuecomment-862627165 https://github.com/CodedSakura/FabricCrossDimTPFix/blob/master/src/main/java/eu/codedsakura/fabriccrossdimtpfix/mixin/TPMixin.java

I hope I came to the right place now for this issue :)

**Comment by Pyrofab** [comment]
Thanks for the detailed issue ! I'll try to get a patch out soon. In the meantime, you should be able to leave the world and join back to fix it.
